### ISSUE TITLE
No Output Directory named "public" found after the Build completed.

### ISSUE THREAD

**Issue by resourceldg** [Saeris/apollo-server-vercel#5]
First thanks for your time!
this project is very interesting...
I am getting the following error when trying to deploy
S:O Ubuntu 18.04
node version  12.18.03

steps
` git clone <this repo> `
`  npm install `  instead of ` npm install --save @saeris/apollo-server-vercel graphql ` <- not working for me
` npm start `

**No Output Directory named "public" found after the Build completed**.

maybe this error is caused by a error configuration in the vercel.json file...

thanks

**Comment by agustif** [comment]
Hey I think you're mixing up (this repo) and doing npm install or yarn add is the same thing.

Just copy the example from the docs on a fresh npm init. / create-next-app and do yarn add /or npm install --save @saeris/apollo-server-vercel graphql

**Comment by Saeris** [comment]
I can see how the docs for this repo may be confusing (there isn't very clear separation between usage and how to contribute). Next week I'll give them an update so it's more clear how you would use this library for new + existing apps. I didn't add them up front since quite honestly I'm new to Next/Vercel myself.

As @agustif suggested, you can create a new Next app and add an API route as described in their [documentation](https://nextjs.org/learn/basics/api-routes) or you can deploy serverless functions to Vercel without using Next by following this [guide](https://vercel.com/docs/serverless-functions/introduction). Once you have a new/existing project, that's when you would add this as a dependency and start building out your graphql server.

You would only clone this repo if you wanted to contribute to development of this library.

**Comment by Saeris** [comment]
Added to the documentation. Hopefully it'll make it clearer how to get started!
