### ISSUE TITLE
does it support subscription?

### ISSUE THREAD

**Issue by hyusetiawan** [Saeris/apollo-server-vercel#6]
because i had to do the custom server route to support it manually

**Comment by Saeris** [comment]
Shot answer: No it does not

Why: Vercel is a serverless functions platform that to my knowledge runs on top of AWS, similar to Netlify and other platforms that offer lambda function deployments. All of these do not support subscriptions because the lifetime of a serverless function starts when a request comes in and ends when that a response to that request is returned by the function. Subscriptions require a constant connection to the server, which is not possible with AWS Lambda (which is basically what we are working with here) which has a maximum execution time of 15 minutes (at the time of writing this response).

In fact, this library is itself based on Apollo's Lambda server implementation, which also does not support subscriptions.

I have no plans to make it work. I don't even know how. If at some point in the future `apollo-server-lambda` does support subscriptions, then I will try to add support for it in this library.

If/when that happens, I would still advise you to look into other solutions anyways, because it likely won't be cost effective, as the cost of operating serverless functions is based on execution time, which would leave you very vulnerable to rogue long-lived functions unexpectedly costing you a ton of money. Subscriptions are better suited for managed servers, using an integration such as `apollo-server-express`.

Sorry about that!

**Comment by hyusetiawan** [comment]
thank you for taking the time to write such a thorough explanation :)
I am going to try out this library for an easy vercel deployment + graphql, cheers!

**Comment by Saeris** [comment]
You're welcome! And I'm glad you're giving this library a try. Feel free to report any problems you run into and I'll try my best to help solve it.

**Comment by amitsin6h** [comment]
> Short answer: No it does not
> 
> Why: Vercel is a serverless functions platform that to my knowledge runs on top of AWS, similar to Netlify and other platforms that offer lambda function deployments. All of these do not support subscriptions because the lifetime of a serverless function starts when a request comes in and ends when that a response to that request is returned by the function. Subscriptions require a constant connection to the server, which is not possible with AWS Lambda (which is basically what we are working with here) which has a maximum execution time of 15 minutes (at the time of writing this response).
> 
> In fact, this library is itself based on Apollo's Lambda server implementation, which also does not support subscriptions.
> 
> I have no plans to make it work. I don't even know how. If at some point in the future `apollo-server-lambda` does support subscriptions, then I will try to add support for it in this library.
> 
> If/when that happens, I would still advise you to look into other solutions anyways, because it likely won't be cost effective, as the cost of operating serverless functions is based on execution time, which would leave you very vulnerable to rogue long-lived functions unexpectedly costing you a ton of money. Subscriptions are better suited for managed servers, using an integration such as `apollo-server-express`.
> 
> Sorry about that!

@Saeris very well answered and explained as well
